apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-gateway
  namespace: llm-gateway
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 10
  policy: local
  # policy: cluster | redis
plugin: rate-limiting