apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: proxy-cache-gateway
  namespace: llm-gateway
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: proxy-cache
config:
  response_code:
  - 200
  request_method:
  - GET
  - HEAD
  - POST
  content_type:
  - text/plain; charset=utf-8
  cache_ttl: 300
  strategy: memory