apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-tgw
  namespace: tgw
  labels:
    name: pv-efs-tgw
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: sc-efs-static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e383d0d2309c2131::fsap-02077b62cf9713c0f
    # volumeAttributes:
    #   mounttargetip: 192.168.52.171