apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::928808346782:user/Admin
      username: Admin
    - groups:
      - system:masters
      userarn: arn:aws:iam::928808346782:user/Developer
      username: Developer
  # mapRoles: |
  #   - rolearn: arn:aws:iam::928808346782:role/eksctl-eks-cluster-llm-nodegroup-n-NodeInstanceRole-K2QoqNhxc0EM
  #     username: system:node:{{EC2PrivateDNSName}}
  #     groups:
  #       - system:bootstrappers
  #       - system:nodes