apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-tgw-neuron
  namespace: tgw-neuron
  labels:
    name: pv-efs-tgw-neuron
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: sc-efs-static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e383d0d2309c2131::fsap-0a3f3fe9bcf46d480
    # volumeAttributes:
    #   mounttargetip: 192.168.52.171