apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-efs-tgw-neuron
  namespace: tgw-neuron
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sc-efs-static
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      name: pv-efs-tgw-neuron
      