apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-gp3-claim-kubecost
  namespace: kubecost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: ebs-sc-gp3