apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from the container!' >> /opt/sm_efs/test01.txt"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /opt/sm_efs
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: pvc-efs
