apiVersion: v1
kind: Pod
metadata:
  name: s3-app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from the container!AAAAA' >> /opt/sm_bucket/test06.txt"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /opt/sm_bucket
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-claim
