apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::${AWS_ACCOUNT_ID}:user/Admin
      username: Admin
    - groups:
      - system:masters
      userarn: arn:aws:iam::${AWS_ACCOUNT_ID}:user/Developer
      username: Developer
  mapRoles: |
    - rolearn: arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes