apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-vllm
  namespace: vllm
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e383d0d2309c2131::fsap-0ce60738f502a17ae
    # volumeAttributes:
    #   mounttargetip: 192.168.52.171